[build]
  publish = "Site/public"
  command = """hugo \
  --source Site \
  --config Site/config.toml \
  --themesDir ../.. \
  --theme repo \
  --baseURL https://blog.motionbug.com"""

[build.environment]
  HUGO_VERSION = "0.101.0"
  HUGO_THEME = "repo"
  HUGO_BASEURL = "/"
