baseURL = "https://blog.motionbug.com"
languageCode = "en-uk"
title = "blog ● motionbug"
themesDir = "../.."
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 6

[module]
  [module.hugoVersion]
    extended = true
    min = "0.101.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@motionbug"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showPostsOnHomepage = true
  addFrame = true
  addDot = true
  highlightColor = '#FA2742'