baseURL = "https://blog.motionbug.com"
languageCode = "en-uk"
title = "blog ● motionbug"
themesDir = "../.."
theme = "hugo-winston-theme"

pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true
paginate = 6

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@motionbug"
  showAuthorOnHomepage = false
  showAuthorOnPosts = true
  showIntroContentOnHomepage = true
  showPostsOnHomepage = true
  usePaginationOnHomepage = false
  limitPostsOnHomepage = 3 # only used if usePaginationOnHomepage is false
  sortPostsByDateOldestFirst = false
  addFrame = true
  addDot = true
  highlightColor = '#FA2742'
  baseColor = "#ffffff"
  baseOffsetColor = "#eaeaea"
  dotColor = "#FA2742"
  enableGoogleFonts = true 
  googleFontsUrl = "https://fonts.googleapis.com/css2?family=Poppins:wght@400;700&display=swap"
  fontFamilyHeading = "Poppins"
  fontFamilyParagraph = "Helvetica"
  fontFamilyMonospace = "monospace"

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    name = "Tags"
    identifier = "tags"
    weight = 4
    url = "/tags/"